networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONFIG_PATH: "/root/config/config.yaml"
    ports:
      - "8080:8080"
    networks:
      - my_network
